server:
  port: 8100
spring:
  application:
    name: Bookcase
  datasource:
    driverClassName: org.h2.Driver
    name: Bookcase
    password: stargate stargate
    url: jdbc:h2:.\\db\\Bookcase;CIPHER=AES
    username: Lavina
  jackson:
    default-property-inclusion: non_null
    serialization:
      indent_output: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
